name: Release
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*']
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - uses: NuGet/login@v1
        id: login
        with:
          user: tnayuki
      - run: dotnet pack src/Bitsmith.Llvm/Bitsmith.Llvm.csproj -c Release -o out
      - run: dotnet nuget push "out/*.nupkg" -k ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
